# Generated by Django 5.2.8 on 2025-11-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltvtracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hltvtracker.matchteam')),
            ],
            options={
                'unique_together': {('match_team', 'session_key')},
            },
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
