# Generated by Django 5.2.7 on 2026-01-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltvtracker', '0002_vote_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positif'), ('NEGATIVE', 'Négatif'), ('NEUTRAL', 'Neutre')], help_text='Analyse automatique du sentiment du commentaire', max_length=10, null=True),
        ),
    ]
