# Generated by Django 5.2.8 on 2025-11-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltvtracker', '0002_match_team_comment_matchteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='matchteam',
            unique_together={('match', 'team_pos')},
        ),
    ]
